# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ca6450719c484cca9284a9c05b666558
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      max-retries: 3
    #      response-format: json_object
    #      strict-json-schema: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ca6450719c484cca9284a9c05b666558
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
        base-url: https://api.deepseek.com
        api-key: sk-ca6450719c484cca9284a9c05b666558
        model-name: deepseek-reasoner
        max-tokens: 32768
        temperature: 0.1
        log-requests: true
        log-responses: true
        # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-a7b7017286f6402e857b5927df57c411
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: true
      log-responses: true



# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://wang-1312435576.cos.ap-guangzhou.myqcloud.com
    secretId: AKIDgDUWIo32lERItFLAj24qLZXFhtoTr0uY
    secretKey: RcWAYgX8TYNwFI6fz3rPhjU1JLBoCKCq
    region: ap-guangzhou
    bucket: wang-1312435576

# 添加 Pexels 图片搜索配置（需要从 Pexels 获取）
pexels:
  api-key: LPgmGdaxpXOPpc0LiksKkWpeG9mnA5Sz2hIQKTlCMBtcAlYkuWvZQbyI

# 阿里云 DashScope 配置
dashscope:
  api-key: sk-a7b7017286f6402e857b5927df57c411
  image-model: wan2.2-t2i-flash
